### ISSUE TITLE
How do i parse following xml? 

### ISSUE THREAD

**Issue by Frankenstein666** [nmdias/FeedKit#100]
```
<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns='http://www.w3.org/2005/Atom'>
<entry>
		<title>Blues</title>
		<image>https://i.ytimg.com/vi/HeOidBAeyQo/default.jpg</image>
		<link href='https://rss.itunes.apple.com/api/v1/us/itunes-music/top-songs/all/50/explicit.atom'/>
</entry>
</feed>

```

AFAIK, current framework does not support image namespace.
is there a way i can access the value inside the <image></image> tag?

**Comment by nmdias** [comment]
Hi, @Frankenstein666

At the moment there is no support for custom elements in FeedKit.. it would be a nice feature to have, however 🤔

As far as I know, the Atom namespace does not have a top level image element. It does however have an icon and logo elements, according to the specification.

Cheers
