### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=256

### ISSUE THREAD

**Issue by sifisov** [nmdias/FeedKit#101]
Firstly, thank you so much for this library! It has saved us lots of time. 

I've been successfully retrieving the feeds both http and https but for some reason, there's one particular feed that's giving me trouble and it keeps giving the following error: Error Domain=NSCocoaErrorDomain Code=256. Error Domain=NSCocoaErrorDomain Code=256 "The file “podcast” couldn’t be opened." UserInfo={NSURL=http://auraawakening.com/feed/podcast/}

The feed works in other rss readers..

All of the other feeds seem to work just fine.

**Comment by nmdias** [comment]
Hi, @sifisov 

I'm glad you found it useful 😸 

I have attempted to parse the `http://auraawakening.com/feed/podcast/` URL, from the latest published version using `pod try FeedKit`. 

I replaced `http://images.apple.com/main/rss/hotnews/hotnews.rss` in `the FeedTableViewController` with `http://auraawakening.com/feed/podcast/` and added the `Allow Arbitrary Loads` to `App Transport Security Settings` in the info.plist file, so as to handle non `https` URLs. I then saw the feed being correctly parsed in an iOS 13 Simulator. I was not able to reproduce the issue on my end,

Is it possible the server was temporarily not serving that content? Could you please try as I described above, and if it doesn't work, also try to do a `curl http://auraawakening.com/feed/podcast/` to see if it fetches that feel correctly. 

Thanks

**Comment by sifisov** [comment]
Thank you so much! Looks like there were two problems from my end.
1) I had a line of code that converted all http and added "s" at the end. 
2) So even though "Allow Arbitrary Loads" was set to YES... The changing of http to https was causing the error.

Completely a mistake on my end. It works Perfectly now!

Thanks Nuno!
