### ISSUE TITLE
All Feed Items return a nil pubDate

### ISSUE THREAD

**Issue by fabianpimminger** [nmdias/FeedKit#102]
I'm having an issue where all feeds (even in the iOS example project, http://images.apple.com/main/rss/hotnews/hotnews.rss) don't have a pubDate in the items.

Is there a known issue here? Any tips what I'm doing wrong? 

I'm using the latest Xcode and building for an iOS 13.1.2 device

**Comment by nmdias** [comment]
Hi, @fabianpimminger 

There seems to be some odd bug in Xcode 11, I'm seeing what I believe you're seeing. When I inspect the pubDate and lastBuildDate variables using a breakpoint, they are showing nil.

However, just try and print them out. They are there! So weird...

![Screenshot 2019-10-10 at 09 17 56](https://user-images.githubusercontent.com/2228069/66551226-f3112e80-eb3e-11e9-8c62-8cb44d93e4fa.png)

**Comment by fabianpimminger** [comment]
@nmdias ahhh … thanks!  Yes, you're totally right - I just used the inspector to look at the variables. I can confirm that the values are present when printing them out. 👍
