### ISSUE TITLE
Feed Not Showing All Articles

### ISSUE THREAD

**Issue by CryptoZinks** [nmdias/FeedKit#108]
The feed not showing all the articles on the site: https://www.cryptozink.io/feed/. Am I missing something or it's supposed to work that way?

**Comment by tarjamorgado** [comment]
It will only show the articles provided in the RSS XML (usually the first 10 ou 20), not all articles on the website. You should check if the source website allows for pagination of some sort, so you can get more articles.

Closing

**Comment by CryptoZinks** [comment]
That makes sense, thank you.  

On 2020-04-02 19:25, Tarja Morgado wrote:

> It will only show the articles provided in the RSS XML (usually the first 10 ou 20), not all articles on the website. You should check if the source website allows for pagination of some sort, so you can get more articles. 
> 
> Closing 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

-- 
Regards, 
Mathieu Louis 

================================
CryptoZink.io
Cryptocurrency Price Index, Charts, 
Market Caps, News, Exchanges 
https://www.CryptoZink.io
================================  

Links:
------
[1] https://github.com/nmdias/FeedKit/issues/108#issuecomment-608143730
[2]
