### ISSUE TITLE
Feed output doesn't include itunes:title

### ISSUE THREAD

**Issue by lepolt** [nmdias/FeedKit#112]
I am parsing an RSS feed and `title` works, but there is no value for `<itunes:title>` tags

**Comment by lepolt** [comment]
Hi, I was testing this out tonight and it still doesn't work. I think handling `/rss/channel/item/itunes:title` is still missing from RSSPath.swift. If I have some time tomorrow I'll see if I can fix it!

**Comment by tarjamorgado** [comment]
I made sure to add a unit test for that element. Not sure what's missing 🤔 Go for it.
