### ISSUE TITLE
Feature request: access to HTTPURLResponse for downloaded feed

### ISSUE THREAD

**Issue by algrid** [nmdias/FeedKit#129]
Sometimes it can be useful to know what HTTP headers server has returned with the feed data. I'm particularly interested in "Etag" and "Last-Modified" headers. It would be nice to include this data into the result of `parseAsync` for parser instances initialized with feed URL.

**Comment by keirmot** [comment]
+1 to this.
Getting and even passing HTTP Headers would be a really good feature.

**Comment by keirmot** [comment]
@algrid there's a workaround for this. The documentation on GitHub doesn't mention it, but the parser has a initialiser that takes Data. 

You can just make your own network calls and parse the data afterwards.

Hope it helps.

**Comment by nmdias** [comment]
Such feature would probably be out of the scope of this framework. Thank you, @algrid and @JoaoCPires for helping out. Closing this for now.
