### ISSUE TITLE
Swift import Error,Those are error message

### ISSUE THREAD

**Issue by IosSuperman** [nmdias/FeedKit#133]
Undefined symbol: nominal type descriptor for FeedKit.RSSFeedItem

Undefined symbol: protocol conformance descriptor for FeedKit.ParserError : Swift.Error in FeedKit

Undefined symbol: FeedKit.FeedParser.__allocating_init(URL: Foundation.URL) -> FeedKit.FeedParser

Undefined symbol: type metadata accessor for FeedKit.RSSFeedItem

Undefined symbol: type metadata accessor for FeedKit.FeedParser

Undefined symbol: type metadata for FeedKit.ParserError

**Comment by GarthSnyder** [comment]
What platform? What versions? What context?

**Comment by briannadoubt** [comment]
I would guess your Podfile or package isn't set up right, but from a "reference not found" error, could be a myriad of things.
