### ISSUE TITLE
how to get image from this xml data

### ISSUE THREAD

**Issue by iqbal92** [nmdias/FeedKit#14]
<a class=\"asset-img-link\" href=\"http://ideas.typepad.com/.a/6a00d83451bb7469e201b7c8e11fbc970b-pi\" style=\"display: inline;\"><img alt=\"Brandon+saigeon1\" border=\"0\" class=\"asset  asset-image at-xid-6a00d83451bb7469e201b7c8e11fbc970b image-full img-responsive\" src=\"http://ideas.typepad.com/.a/6a00d83451bb7469e201b7c8e11fbc970b-800wi\" title=\"Brandon+saigeon1\" /></a>

after using content?.contentEncoded then after i got this data so, how can i get specific image link in this data

**Comment by nmdias** [comment]
@iqbal92 a regular expression seems appropriate here. Try this [live demo](http://www.rubular.com/r/dxE4dKMCe6)
