### ISSUE TITLE
Documentation domain has been suspended

### ISSUE THREAD

**Issue by rafaelclaycon** [nmdias/FeedKit#141]
Just tried to access the Docs from the README (http://cocoadocs.org/docsets/FeedKit) and got this:
<img width="1552" alt="Captura de Tela 2022-01-23 às 20 34 32" src="https://user-images.githubusercontent.com/5100081/150702695-eae6fcd3-74be-413c-8e55-cf26dd422911.png">
Can something be done about this?

**Comment by nmdias** [comment]
Thank you for the issue @rafaelclaycon 

I believe that service was deprecated in cocoa pods. Closing. 

Cheers
