### ISSUE TITLE
iOS16 crashed

### ISSUE THREAD

**Issue by jiangdi0924** [nmdias/FeedKit#144]
FeedKit is good package, it's very useful , but in iOS16 app crashed
- Xcode14 beta
- iOS 16

`error build: Invalid Swift parseable output message (malformed JSON): `{
  "kind": "began",
  "name": "compile",
    "-ivfsoverlay",
    "-Xcc",
    ......
    ...about FeedKit info...
    ......
  ],
  "pid": -1092,
  "process": {
    "real_pid": 4772
  }`
`

**Comment by GarthSnyder** [comment]
Thanks for the report, I will see if I can reproduce. PRs also welcome if you want to take a more detailed look.
