### ISSUE TITLE
RSS Media

### ISSUE THREAD

**Issue by damienissa** [nmdias/FeedKit#16]
What about rss media parsing?
I didn't see how I can get thumbnail from RSSFeedItem.
You can research this spec: http://www.rssboard.org/media-rss
items for test:

[testRss.txt](https://github.com/nmdias/FeedKit/files/1018888/testRss.txt)

**Comment by damienissa** [comment]
Thanks. And I have a question. How I can get item XML value? Maybe your library have some private method? I want to try parse image from current XML.

**Comment by nmdias** [comment]
What element or attribute exactly are you trying to get? Does it belong to the spec, or is it contained XML data within an Element?

See if #14 helps

**Comment by damienissa** [comment]
@nmdias I mean that "media" is element of feed item. "media" can has many optional attributes. I try to use "media:thumbnail". But another users maybe need to use other attributes.

**Comment by nmdias** [comment]
@damienissa you can't at this time. Currently, FeedKit doesn't support the Media namespace, so there aren't any private methods or properties that would allow you to read them.

I'll make sure to include this feature in the 6.0.0 release.

**Comment by nmdias** [comment]
The RSS Media Namespace is now available in the master branch. It will also be available in the future 6.0.0 release.
