### ISSUE TITLE
Support JSON Feed

### ISSUE THREAD

**Issue by pjctech** [nmdias/FeedKit#17]
It would be awesome if FeedKit supports [JSON Feed](https://jsonfeed.org).

There is already a [Swift parser](https://github.com/totocaster/JSONFeed) for JSON Feed.

**Comment by nmdias** [comment]
I'm trying to finish up JSONFeed support, can anybody help me figure out why the unit tests are failing on Travis?

**Comment by nmdias** [comment]
JSON Feed is now available on the master branch.
