### ISSUE TITLE
Unable to use in Objective-C project

### ISSUE THREAD

**Issue by Supertecnoboff** [nmdias/FeedKit#19]
Hi,

Is there a way I can use the framework in my Objective-C project? I imported the FeedKit framework into my Xcode project and opened it up. I saw that it has a ```FeedKit-Swift.h``` bridging header?

Is there a way I can use that, to call the Swift classes from my Objective-C code? For example I want to create an instance of the FeedParser class and call the ```FeedParser(URL: URL)?.parse``` method.

Thanks for your time, Dan.

**Comment by nmdias** [comment]
Hi @Supertecnoboff 

Sorry for the late reply. So I did a quick look, and from what I gathered, I would have to make all that I expose in FeedKit, attributed with an @objc. That by it self would force me to inherit from an NSObject, and thus, exposing dozens of methods and properties from Obj-C. This is something I would not like to do with FeedKit.

However, 

Give it a run and see if it fits your needs. Create a new Obj-C project. Name it `FeedKitObjC ` and add a Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'FeedKitObjC' do
  pod 'FeedKit', '~> 5.0'
end
```

`#import <FeedKit/FeedKit-Swift.h>`

Then prefix everything that you need to publicly access. For example:

```swift
// This
open class FeedParser { }

// would become this:
@objc open class FeedParser: NSObject { } 


Change the sources directly under the `Pods/FeedKit` folder, just to give you a taste. Force Unlock the files if it complaints about changing the source code. We just want to try it out. 

If it works for you, I would recommend forking the project, and then update the Podfile to your fork directly.

Cheers and best of luck
