### ISSUE TITLE
Crash when no internet is available

### ISSUE THREAD

**Issue by dkcas11** [nmdias/FeedKit#30]
Hi,

It seems a call will crash if there is no internet connection available.

Right now my setup is like this:
```
guard let url = URL(string: rssEndpoint) else {
	print("Endpoint format invalid.")
	return
}

guard let feedParser = FeedParser(URL: url) else {
	print("Failed to create parser from endpoint.")
	return
}

feedParser.parse({ (result) in
        ....
})
```

Where the error occurs in my second guard, when creating the parser itself.
Inspecting the error further in XCode shows that it crashes on line 56 in FeedParser.swift, in your guard statement.

**Comment by dkcas11** [comment]
Sorry, i'm an idiot. I was still on version 5.1.0. Updated now at it looks to work fine :)

**Comment by nmdias** [comment]
Please try to update FeedKit to version ~> 6 and get back to me. This should have been resolved in issue #4

**Comment by dkcas11** [comment]
It seems there might still be some issues here. I parse with the parseAsync. Shouldn't it be fine to just use the DispatchQueue.main?

I run it off my viewDidAppear, but it still seems to block the UI while parsing.

**Comment by nmdias** [comment]
If it's a different problem please consider opening another Issue. Thanks 🙏
