### ISSUE TITLE
Unable to fetch image from featureimg tag

### ISSUE THREAD

**Issue by Kiran8899** [nmdias/FeedKit#32]
The library works fine with text. Is there any way to fetch images and show too?

**Comment by nmdias** [comment]
Hi @Kiran8899, can you elaborate? 

I never heard of the `featureimg` element. Is this an extension to the RSS spec? I saw a similar question on [SO](https://stackoverflow.com/questions/45251381/rss-feed-unable-to-parse-featureimg-tag-swift-3). Could you provide the feed in question or see if it declares some additional namespace?
