### ISSUE TITLE
Media namespace not available on AtomFeed

### ISSUE THREAD

**Issue by valeriomazzeo** [nmdias/FeedKit#34]
Currently, media attributes are parsed only as part of an RSSFeedItem.

I may be wrong, but perhaps it should be possible for something like this:

```xml
<media:thumbnail width="40" height="40" url="https://secure.gravatar.com/avatar/1234"/>
```

to be contained inside an `AtomFeedEntry`.

**Comment by nmdias** [comment]
Well, of the top of my head, I don't see any reason for Atom not to be able to extend the Media namespace. I'll add support as soon as I get some time on my hands.

**Comment by valeriomazzeo** [comment]
thanks @nmdias, do you have any idea when will you be able to do it?

**Comment by nmdias** [comment]
Honestly, I was waiting for Xcode 9 GM. I don’t even have Xcode 8 anymore.

I’ll try to do it this weekend 👍

**Comment by valeriomazzeo** [comment]
@nmdias that would be great, please let me know if you need any help

**Comment by nmdias** [comment]
Hi @valeriomazzeo,  

Whenever you get that chance, give the master branch a go and check if it's working well for you. 

Thanks

**Comment by valeriomazzeo** [comment]
@nmdias that's great, just tried and it works nicely.

I would really appreciate if you could release a new version on cocoapods, as I have a podspec that depends on `FeedKit` unfortunately I can't make the dependency point to the `master` branch.

**Comment by nmdias** [comment]
@valeriomazzeo -> [6.1.2](https://github.com/nmdias/FeedKit/releases/tag/6.1.2) is now out in the wild.
