### ISSUE TITLE
Crashes when feed url returns html

### ISSUE THREAD

**Issue by jimijon** [nmdias/FeedKit#36]
OK I am using pod 6

sometimes this url: http://www.newsbtc.com/feed/

will return HTML and quickly crash 👍 

            FeedParser(URL: feedURL)!.parseAsync { (result) in

Normall it returns an RSS feed but through my testing it will block too many transactions and return HTML saying you need to talk to support.

**Comment by nmdias** [comment]
Hi @jimijon, thanks for reporting this. 

Can you get me the HTML that is causing this to crash? 

Thanks

**Comment by jimijon** [comment]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
	<title>Your access to this site has been limited</title>
</head><body>
<h1>Your access to this site has been limited</h1>
<p>Your access to this service has been temporarily limited. Please try again in a few minutes. (HTTP response code 503)</p>
<p>Reason: <span style="color: #F00;">Advanced blocking in effect.</span></p>
<p style="width: 600px;"><b>Important note for site admins: </b>If you are the administrator of this website note that your access has been limited because you broke one of the Wordfence advanced blocking rules.
	The reason your access was limited is: <b>"Advanced blocking in effect."</b>.
	<br /><br />
	If this is a false positive, meaning that your access to your own site has been limited incorrectly, then you
	will need to regain access to your site, go to the Wordfence "options" page, go to the section for Rate Limiting Rules and disable the rule that caused you to be blocked. For example,
	if you were blocked because it was detected that you are a fake Google crawler, then disable the rule that blocks fake google crawlers. Or if you were blocked because you
	were accessing your site too quickly, then increase the number of accesses allowed per minute.
	<br /><br />
	If you're still having trouble, then simply disable the Wordfence advanced blocking and you will
	still benefit from the other security features that Wordfence provides.
</p>

	<br />

	If you are a site administrator and have been accidentally locked out, please enter your email in the box below and click "Send". If the email address you enter belongs to a known site administrator or someone set to receive Wordfence alerts, we will send you an email to help you regain access. <a href="https://docs.wordfence.com/en/Help!_I_locked_myself_out_and_can't_get_back_in._What_can_I_do%3F" target="_blank" rel="noopener noreferrer">Please read this FAQ entry if this does not work.</a>
	<br /><br />
	<form method="POST" id="unlock-form" action="#">
		<input type="hidden" name="nonce" value="c710af1d940b4ca3cc46ea9721f12686efa0ba7fb3eb3ab62fbb7b53f0253ff4" />
		<input type="text" size="50" name="email" id="unlock-email" value="" maxlength="255" />&nbsp;<input type="submit" name="s" id="unlock-submit" value="Send me an unlock email" disabled />
	</form>
	<script type="application/javascript">
		(function() {
			var textfield = document.getElementById('unlock-email');
			textfield.addEventListener('focus', function() {
				document.getElementById('unlock-form').action = "http://www.newsbtc.com/" + "?_wfsf=unlockEmail";
				document.getElementById('unlock-submit').disabled = false;
			});
		})();
	</script>
<br /><br />

<p style="color: #999999;margin-top: 2rem;"><em>Generated by Wordfence at Sat, 2 Sep 2017 18:25:08 GMT.<br>Your computer's time: <script type="application/javascript">document.write(new Date().toUTCString());</script>.</em></p>
</body></html>

**Comment by nmdias** [comment]
Hi @jimijon,

Still not crashing here. Is that clear text HTTP? If so, make sure you disable App Transport Security for your domain.

Try adding this to your Info.plist file and give it a ago. 

```swift
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key><true/>
</dict>
```

If it does, make sure to change it to **only allow the domain that you need** in clear text.

**Comment by jimijon** [comment]
Ok I called it with the optional and it doesn't crash:

 FeedParser(URL: feedURL)?.parseAsync { (result) in
                self.feed = result.rssFeed
                self.tableView.reloadData()
            }

**Comment by CryptoZinks** [comment]
Same thing happening to my feed. https://www.cryptozink.io/feed/
