### ISSUE TITLE
Load more than 10 feed items using an index

### ISSUE THREAD

**Issue by ryanoconnor7** [nmdias/FeedKit#37]
As far as I can tell, FeedKit only fetches the last 10 RSS items in a feed. 

Is it possible/would you consider adding an index to access, for example, posts 11-20? I think an index would be the best way to solve this because having just a number of items to load option would make the first load slower. I’d rather load more items as needed.

**Comment by nmdias** [comment]
Hi @ryanoconnor7, 

FeedKit will fetch as many items as the feed provides. If the contents of a URL has 26 entries or items, then it will parse those 26 entries or items. If 10, then only 10 will be parsed.

However, if the feed in question provides pagination capabilities, then they probably should be specified in the URL of the feed. 

Like so:

```
http://images.apple.com/main/rss/hotnews/hotnews.rss?page=2
```
I don't believe there is a standard for pagination in RSS. And most feed providers don't offer this kind of capability unless it's a specific need and requires implementation of an edge case not within the standard. 

Is this a custom feed you're using? Can you share the link if it's public? 

Cheers

**Comment by ryanoconnor7** [comment]
Ah, I see. It may be a limitation of Wordpress as that is what I am getting from. 

Here’s the link:

https://chstarmac.com/rss

**Comment by ryanoconnor7** [comment]
Yep. Wordpress has a limit of 10 posts, and I can get more posts by calling:

https://chstarmac.com/rss?page=2 

Sorry I didn’t look into that first! Thanks!

**Comment by ryanoconnor7** [comment]
Just for future reference — I made a typo in the link, but it should be:

https://chstarmac.com/rss?paged=2

For anyone who wants to access greater than 10 posts using Wordpress.

**Comment by nmdias** [comment]
Glad you sorted it out. 

Happy parsing 😃

**Comment by BhavinBhadani** [comment]
So Is this support WordPress blogs parsing? 

Maybe not as I checked "https://public-api.wordpress.com/rest/v1.1/sites/en.blog.wordpress.com/posts/?page=1&fields=ID,author,title,URL,content,discussion,featured_image,post_thumbnail,tags,discussion,date,attachments" that won't work.

So, Is there future enhancement for this?

**Comment by BhavinBhadani** [comment]
@nmdias Is this also compatible way to parse your Wordpress blog's feed? as I tried and didn't work but it's worked with [obj-c parser](https://github.com/mwaterfall/MWFeedParser)
