### ISSUE TITLE
Crashes when trying to parse a feed URL offline

### ISSUE THREAD

**Issue by enricenrich** [nmdias/FeedKit#4]
For some reason, when trying to parse a URL in offline mode with FeedKit, the app crashes. If there's an Internet connection it works as expected.

**Comment by nmdias** [comment]
I can't help but wonder if this is an error in the Foundation's XMLParser. I was able to replicate the crash, and it happens when calling 

`Parser(contentsOf: URL)`

The 'Parser' class is actually a subclass of the foundation's XMLParser, and this is nothing but a call to a convenience initializer of the XMLParser itself.

Documentation says that it should return:

> An initialized NSXMLParser object or nil if an error occurs.

And there is a check for that that propagates the failable initializer:

```
    public init?(URL: URL) {
        guard let parser = Parser(contentsOf: URL) else {
            return nil
        }
        self.parser = parser
    }
```

I'll have to dig deeper..

**Comment by enricenrich** [comment]
I tried to call directly `XMLParser(contentsOf: URL)` and it didn't crash. So it's something in the library, not XMLParser.

**Comment by nmdias** [comment]
Just tried to isolate the issue:

Apparently this works:

```
let feedURL = URL(string: "http://images.apple.com/main/rss/hotnews/hotnews.rss")!

if let parser = XMLParser(contentsOf: feedURL) {
        print("Got instance \(parser)")
}

```

This does not:

```
class Parser: XMLParser { }

let feedURL = URL(string: "http://images.apple.com/main/rss/hotnews/hotnews.rss")!

if let parser = Parser(contentsOf: feedURL) {
        print("Got instance \(parser)")
}
```

Any ideas?

**Comment by nmdias** [comment]
As a temporary solution, i found that you can safely do this:

if let data = NSData(contentsOf: feedURL) as? Data {
    
    FeedParser(data: data).parse({ (result) in
        // do your thing
    })
            
}

**Comment by enricenrich** [comment]
Maybe it's related to overriding

```
override init(data: Data) {
    super.init(data: data)
    self.delegate = self
}
```

Did you try to remove it to see if it crashes?

**Comment by nmdias** [comment]
Yes, I did. 

Take this example for instance:

```
class Parser: XMLParser { }

let feedURL = URL(string: "http://images.apple.com/main/rss/hotnews/hotnews.rss")!

if let parser = Parser(contentsOf: feedURL) {
    print("Got instance \(parser)")
}
```

In this example, the `Parser` class is not actually overriding anything. All it's doing is saying: Hello! I'm a subclass of XMLParser. Nothing else. And it still crashes!

I'll keep digging some more...

**Comment by nmdias** [comment]
Submitted a bug report to Apple with nº 28904764 and opened up a [Radar](https://openradar.appspot.com/radar?id=4946181125832704) to this issue.

In the meantime I'll cook a workaround, using NSData's `contentsOf` init and release a fix.

**Comment by RJiryes** [comment]
Hi, any updates? Thanks!

**Comment by WFurthado** [comment]
I got the same error. I just replaced the link with

`feedURL = NSURL(string:"http://images.apple.com/main/rss/hotnews/hotnews.rss#sthash.fuVEonEt.dpuf")!`

Error gone...

**Comment by alvarozizou** [comment]
Hi, any update? thanks

**Comment by nmdias** [comment]
Apple engineers aren't able to reproduce this bug, and I just don't have time to go back and forward in the bug reporter with them.

You can always use the workaround described above.

I'm also working on version 6 of FeedKit, that will bypass this bug. Time however isn't much so it's taking awhile.
