### ISSUE TITLE
Not Able to Check Multiple Items in a Feed

### ISSUE THREAD

**Issue by theindiandev1065** [nmdias/FeedKit#40]
Hello! In my app, I want to display the first 10 different items in a feed in a UICollectionView. I can only access the first item in a feed shown in your documentation. How would I be able to gather the first 10 items and add them to an array?

**Comment by nmdias** [comment]
Hi @theindiandev1065,

The example show in the documentation...

```swift
let item = feed.items?.first
```
...accesses an array of `items`. You can iterate over these:

```swift
feed?.items?.forEach({ (item) in
    print(item.title)
})
```

Or access them Individually:

```swift
self.feed?.items?[0].title // first
self.feed?.items?[1].title // second
// ... and so on
```

**Comment by theindiandev1065** [comment]
Thanks!
