### ISSUE TITLE
Task Failed 

### ISSUE THREAD

**Issue by AwmirHN** [nmdias/FeedKit#42]
```
NSURLConnection finished with error - code -1001
HTTP load failed (error code: -999 [1:89])
```

What should I do ?

**Comment by nmdias** [comment]
Hi @AwmirHN,

My guess is that you may be trying to access an HTTP resource without adding an exception to App Transport Security.

Try adding this to your Info.plist file and give it a ago. 

```swift
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key><true/>
</dict>
```

If it does work, make sure to change it to **only allow the domain that you need** in clear text.

If it doesn't work, please provider some more details, the console output, the stack trace...

Thanks

**Comment by AwmirHN** [comment]
I have used this ! 
But it sometimes work and sometimes it doesn't work and failed with that error :(

**Comment by nmdias** [comment]
This seems related to the network connection, not necessarily to the parser. If you're using the URL directly onto the Parser, make sure that you are able to actually read that URL. 

Or, a better alternative: for cases like this, it's most likely better to first and foremost, load the actual XML/JSON `Data` and error handle any networking errors, and feed that `Data`to the parser's `public init?(data: Data)`

**Comment by AwmirHN** [comment]
Thanks for your help.

You are the best 🥇
