### ISSUE TITLE
xml encoding

### ISSUE THREAD

**Issue by MizuNoLorien** [nmdias/FeedKit#44]
Hi, while using your library I came across a feed whose xml is encoded using ISO-8859-1 instead of UTF-8. this makes the FeedDataType return nil and so does te FeedParser constructor, making it impossible to parse the feed. is there anyway you could add support for other encoding standards for xml? Thank you in advance

**Comment by nmdias** [comment]
Hi @MizuNoLorien,

I don't got the time right now. I'm also on vacation. For the time being, may I suggest a temporary alternative? Maybe extend FeedParser with a convenience initialiser, pass an XML string, manually convert the string to UTF-8, then to a Data object and pass that to the FeedParser's init(data:)

It should work. If not, I'll probably pick this up next year only.

A Unit Tested PR is also welcomed.

Hope that helps.

Cheers
