### ISSUE TITLE
FeedParser(URL: url) unexpectedly fetches data for url upfront causing UI hang

### ISSUE THREAD

**Issue by bhlvoong** [nmdias/FeedKit#45]
I'm not exactly sure the reasoning for the upfront fetching of the data found at "url".  Most users, like myself, probably assume that parseAsync performs the fetch and parsing together.

**Comment by BhavinBhadani** [comment]
@bhlvoong  Do u found anything?

**Comment by BhavinBhadani** [comment]
Any solution because it does crashed eventually

**Comment by BhavinBhadani** [comment]
Right .. same issue here, it will take lots of time

**Comment by nmdias** [comment]
Hi @bhlvoong and @BhavinBhadani,

It's because it's invoking 'Data(contentsOf: URL)' right after providing FeedParser with a URL. Sorry for taking so long. I will try and address this issue in the next couple of days. 

Thank you for reporting the issue

Cheers
