### ISSUE TITLE
can we get the images from description?

### ISSUE THREAD

**Issue by BhavinBhadani** [nmdias/FeedKit#49]
Can we fetch and get media files easily from the description. For e.g. https://blog.google/rss/ and I want images to be fetched from description

**Comment by nmdias** [comment]
Hi @BhavinBhadani,

No, that's not possible with FeedKit. However, you can use something like [SwiftSoup](https://github.com/scinfu/SwiftSoup) to parse the HTML DOM, after parsing the Feed with FeedKit.

Cheers
