### ISSUE TITLE
Operation queue, cancel

### ISSUE THREAD

**Issue by vaderdan** [nmdias/FeedKit#5]
Hi, I've question.

How I can use this library with NSOperationQueue and is there any way to cancel FeedKit parse request.
is the XMLParser's abortParsing method appropriate for that?

**Comment by nmdias** [comment]
Hi @vaderdan,

I've just exposed the XMLParser's `abortParsing` method in the `FeedParser` class [here](https://github.com/nmdias/FeedKit/commit/2733194a77e6d6b7c41c6ee7576285f9739959e7)

It will be available on the next release. For now you can checkout the master, in order to get it. 

As for the operation queue, I guess it would be vey similar to the example provided [here](https://github.com/nmdias/FeedKit#background-parsing) with Swift 3's dispatch queue.

I haven't tried this myself, but it should go along the line of:

```
let queue = OperationQueue()

queue.addOperation() {
    // Run parsing in the background
    FeedParser(URL: feedURL)!.parse { (result) in
        OperationQueue.main.addOperation() {
            // Perform updates in the main queue when finished
        }
    }
}

```

**Comment by vaderdan** [comment]
Thanks for letting me to try the `abortParsing` method!! 😄
I tested it a bit here is what I found:

I had a little bit of hard time wondering about this:
From what I saw from the `FeedKit` Core, the `FeedParser(URL: feedURL)` initialization is calling 
the `XMLParser`'s `public convenience init?(contentsOf url: URL)` and it is downloading the xml document during the object initialization not the `parse`  method.

The problem is why is the heavy lifting (downloading the content) done during the initialization of the FeedParser object, but not in the `parse` method.




I've tested the operation queue and it works.
Here is some sample of the `FeedKitOperation` class

```
import Foundation
import FeedKit

public class FeedKitOperation: ConcurrentOperation {
    var parser:FeedParser?
    let url:URL
    let completionHandler: (Result) -> Void


    public init(url:URL, _ completion: @escaping (Result) -> Void) {
        self.url = url
        self.completionHandler = completion
        super.init()
    }
    
    override public func main() {
        self.parser = FeedParser(URL: url)
        self.parser?.parse({ result in
            var result = result
            self.state = .finished
            
            if self.isCancelled {
                result = .failure(NSError.init(domain: "Cancelled", code: -1, userInfo: nil))
            }
            
            self.completionHandler(result)
        })
    }
    
    override public func cancel() {
        super.cancel()
        parser?.abortParsing()
    }
}
```

I used this gist https://gist.github.com/calebd/93fa347397cec5f88233
as `ConcurrentOperation` class.

**Comment by vaderdan** [comment]
My tests are in this repository https://github.com/vaderdan/FeedKitTest

**Comment by vaderdan** [comment]
Can I close this issue?

**Comment by nmdias** [comment]
Cool, thanks for sharing :)
