### ISSUE TITLE
Custom Attributes + CDATA Encoding

### ISSUE THREAD

**Issue by Pilot1000** [nmdias/FeedKit#63]
I apologize if this question is easily solvable,

In my XML document I have a custom attribute <dc:creator> (which specifies the author) that is also encoded in CDATA. I was wondering how I would use FeedKit with custom attributes and when they're encoded in CDATA.

**Comment by nmdias** [comment]
Hi @Pilot1000,

Have you tried parsing the feed? dc:creator is an elements of the Dublin Core namespace so FeedKit should handle it fine, even if it's inside a CDATA block.

Have a look at this [section](url
https://github.com/nmdias/FeedKit#rss) of the README file. Both the channel and channel's items have a `dublinCore` property.

Cheers

**Comment by Pilot1000** [comment]
I didn't understand what dublinCore was so I didn't even think of checking what was inside it in the first place. It works now, thank you for an amazing pod!

**Comment by Pilot1000** [comment]
Before this is closed, I have a similar issue with itunesImage. It seems you can't convert it to a string or anything other than ItunesImage. Not sure how you'd use that for images. (In my instance I just need the url as a string).

**Comment by nmdias** [comment]
I'm not sure I understand. But if you only need is the url as a string, then the iTunes namespace should give you that. Have a look at the unit tests for the iTunes Namespace [here](https://github.com/nmdias/FeedKit/blob/master/Tests/iTunesTests.swift).

```swift
        XCTAssertEqual(feed?.iTunes?.iTunesImage?.attributes?.href, "http://www.dancarlin.com/graphics/DC_HH_iTunes.jpg")
```

**Comment by Pilot1000** [comment]
That's exactly what I needed. Thank you!
