### ISSUE TITLE
Get tag not in documentation

### ISSUE THREAD

**Issue by CarioniStefano** [nmdias/FeedKit#65]
Hello,

I'm having some problems with a RSS Feed with some extra tags inside the <item> tag.

<img width="1440" alt="schermata 2018-10-05 alle 11 45 02" src="https://user-images.githubusercontent.com/12976725/46528484-371a8500-c894-11e8-9fb6-556d6084726a.png">

I need to get values inside the red box, any way I can get them with feedkit?

Thanks

**Comment by nmdias** [comment]
Hi @CarioniStefano,

That doesn't seem to be inside any valid rss element, and as such, you won't be able to read that with FeedKit directly.

With that said, you could try a few alternatives:

- Using Apple's own `XMLParser` to get that 
- Search for an XML parser like [SWXMLHash](https://github.com/drmohundro/SWXMLHash). I have never used it, but it seems to be able to handle that.

And the one I would go to, considering you're already tinkering with FeedKit:

- Fork FeedKit, and add those paths highlighted in red to [RSSPath.swift](https://github.com/nmdias/FeedKit/blob/master/Sources/FeedKit/Models/RSS/RSSPath.swift), and then go to [RSSFeed + mapCharacters.swift](https://github.com/nmdias/FeedKit/blob/master/Sources/FeedKit/Models/RSS/RSSFeed%20%2B%20mapCharacters.swift) and add the missing cases you just added to `RSSPath.swift`.

You'll also need to add the corresponding properties to [RSSFeedItem.swift](https://github.com/nmdias/FeedKit/blob/master/Sources/FeedKit/Models/RSS/RSSFeedItem.swift).

I believe it's pretty straight forward and I think I'm not missing anything, but if I did, feel free to ask me and I'll help the best I can.

Cheers
