### ISSUE TITLE
Don't parse some info

### ISSUE THREAD

**Issue by sglushchenko** [nmdias/FeedKit#66]
Hello,

I have feed `https://99bitcoins.com/feed/`

This feed has this block

```
<media:content url="https://www.youtube-nocookie.com/v/zc27UFwGcZo" duration="116">
			<media:player url="https://www.youtube-nocookie.com/v/zc27UFwGcZo" />
			<media:title type="html">Bitcoin News Summary - October 15, 2018</media:title>
			<media:description type="html">Here’s what happened this week in Bitcoin in 99 seconds. ﻿ Major exchange and Tether operator, Bitfinex, has imposed a temporary ban on all fiat deposits. Clients are no longer able to deposit Euros, Dollars, Yen or Pounds to the exchange. Withdrawals are reportedly working normally. Bitfinex has sa</media:description>
			<media:thumbnail url="https://99bitcoins.com/wp-content/uploads/2018/10/zc27ufwgczo.jpg" />
			<media:keywords></media:keywords>
		</media:content>
```

FeedKit can parse media:content with attributes, but can't parse inside media:content. How I can extend your parser and don't touch your code or maybe you add it?

I use CocoaPods, So I can't change your source code locally.

Maybe you can give a full block of XML and each developer can parse it, if it's not standard.

Thanks
Best Regards

**Comment by nmdias** [comment]
Hi, @sglushchenko 

Sorry it took so long. Hope that fixes it.

Thanks
