### ISSUE TITLE
Newbie question.

### ISSUE THREAD

**Issue by Rizora** [nmdias/FeedKit#70]
I'm trying to make a view that load the RSS feed and displays the podcast and the audio file... I'm having trouble implementing that. Is there any documentation or examples you can point me to? Thank you.

**Comment by nmdias** [comment]
Hi @Rizora,

Is this still an issue? The examples shown in the README should suffice. There is also an Example project you can try.

Just run:

```sh
pod try FeedKit
```

After parsing the feed, you should be able to access the desired properties directly, depending on which elements of the RSS's feed you're trying to access. Is there any particular detail you're having difficulty?

Cheers
