### ISSUE TITLE
Trying to run Conversion to Swift 4.2 

### ISSUE THREAD

**Issue by dbadmin** [nmdias/FeedKit#74]
I get this error when trying to run the Conversion to Swift 4.2 and I am using pod install to install.

<unknown>:0: error: module map file 'build/Release-iphoneos/FeedKit/FeedKit.modulemap' not found
<unknown>:0: error: module map file 'build/Release-iphoneos/FeedKit/FeedKit.modulemap' not found
<unknown>:0: error: missing required module 'SwiftShims'

**Comment by nmdias** [comment]
Hi, @dbadmin.

Project as been converted to Swift 4.2 in [commit](https://github.com/nmdias/FeedKit/commit/7e5d0acdee8bec1985d5ce28407b5c24445bdc8d).

Thanks

**Comment by dbadmin** [comment]
I ran the pod update but still can not convert my project to Swift 4.2 because of the error I get.

**Comment by nmdias** [comment]
@dbadmin have you tried deleting your derived data folder? 🤔

**Comment by dbadmin** [comment]
I removed everything in the derived data folder.  I have removed all pods and all files associated then reinstalled all of them.

**Comment by nmdias** [comment]
@dbadmin how about this way, remove FeedKit completely, migrate to 4.2 and then add FeedKit again. 

That will either work, or at least give a glimpse of what’s the issue.

**Comment by dbadmin** [comment]
I was able to run the convert after commenting out FeedKit and SwiftSoup pods. Then I ran pod update to remove them and then commented out all code that used the pods and was able to run the update.  

My Pod file.
platform :ios, '11.2'
target "Test App" do
pod 'Firebase/Core'
pod 'Fabric'
pod 'Crashlytics'
#pod 'FeedKit'
#pod 'SwiftSoup'
end

**Comment by nmdias** [comment]
Good to know! 

Cheers
