### ISSUE TITLE
Can't parse pubDate and else info if it is CDATA encoding

### ISSUE THREAD

**Issue by RayZhao1998** [nmdias/FeedKit#76]
Hello

I have a rss feed. It seems to be CDATA encoding. Its pubDate is like `<![CDATA[ 2018-12-21 11:27:25 +0800 ]]>`.

When I use `rssFeed?.items?.first?.pubDate`, it returns `nil`.

**Comment by nmdias** [comment]
Hi, @RayZhao1998 

Is this still an issue? 

- I find it odd that the date is inside a CDATA Block, but even then, that shouldn't stop FeedKit to attempt to parse the feed. 

- Also, the date doesn't seem to be an RFC822 formatted date. Is this a public feed? If so, could you please share it?

Thanks
