### ISSUE TITLE
RSSFeedItemGUID is being given a wrong value for this rss feed

### ISSUE THREAD

**Issue by pearl7721User1** [nmdias/FeedKit#87]
If you parse this rss feed,
http://allearsenglish.libsyn.com/rss

A wrong value comes in for RSSFeedItemGUID property. It looks like the link value is written for the RSSFeedItemGUID property. It is happening for some recent episodes.

Look at this screenshot.
![Screen Shot 2019-04-03 at 1 09 53 AM](https://user-images.githubusercontent.com/18760280/55418268-48c3b780-55ad-11e9-84c3-8036819cb11b.png)

**Comment by nmdias** [comment]
Hi, @pearl7721User1 

That's because the feed is outputting it like that. 

Try running in the terminal:
```sh
curl http://allearsenglish.libsyn.com/rss
```

Then have a look at the feed:
```xml
<guid isPermaLink="false"><![CDATA[http://allearsenglish.com/?p=6]]></guid>
```

This is perfectly fine, and an acceptable form of a unique identifier for this use case.

**Comment by pearl7721User1** [comment]
Hi, @nmdias 
Turned out it's my mistake. It's all working fine. Thank you for your swift answer.
