### ISSUE TITLE
FeedKit.Result collides with Swift 5 Result

### ISSUE THREAD

**Issue by lauri-koli-vincit** [nmdias/FeedKit#88]

**Comment by subdigital** [comment]
Until the project adopts Swift 5's result you can fully qualify the Swift Result type as needed like this:

```swift
... completion: @escaping (Swift.Result<String, Error>) -> Void 
```

**Comment by nmdias** [comment]
Hi, @lauri-koli-vincit 

We can expect no collisions with Result in the next release of `FeedKit, following f9ae2500e2ef616cfcce361592406c4b03107e18 

Closing for now,
Thanks
