### ISSUE TITLE
Support for RSS 1.0

### ISSUE THREAD

**Issue by mehlkelm** [nmdias/FeedKit#9]
The way I read the README, FeedKit claims to support older RSS versions. It detects RSS 1.0 correctly based on the rdf:RDF tag. The RSSPath class however doesn't handle paths like "/rdf:RDF/channel/title". No information for the following feed can be parsed, for example:
http://rss.slashdot.org/Slashdot/slashdotMain

**Comment by mehlkelm** [comment]
I tried a quick fix/workaround by adding an initializer to RSSPath which re-maps some of the differences:
`init?(rssPath: String) {
  var RSS2mappedPath = rssPath.replacingOccurrences(of: "/rdf:RDF/item", with: "/rss/channel/item")
  RSS2mappedPath = RSS2mappedPath.replacingOccurrences(of:"/rdf:RDF", with:"/rss")
  self.init(rawValue: RSS2mappedPath)
}`
But there are too many item properties packed in attributes instead of XML elements for that… I guess we would need a whole new set of mapping classes for RSS 1.0.

**Comment by nmdias** [comment]
I'll try and cook a fix this weekend. Keep those issues coming if you find more. I appreciate it.

**Comment by aehlke** [comment]
I'm evaluating https://github.com/younata/Muon which claims to support RSS 1.0

**Comment by nmdias** [comment]
Well, this took a while... FeedKit 6.2.0 is out in the [wild](https://github.com/nmdias/FeedKit/releases/tag/6.2.0).
