### ISSUE TITLE
media:content/media:keywords not being picked up

### ISSUE THREAD

**Issue by Snibbler** [nmdias/FeedKit#90]
There are a few elements not being picked up in the RSS Media namespace:

media:content/media:keywords
media:content/media:poster
media:content/media:original_thumbnail
media:content/media:category

**Comment by nmdias** [comment]
Hi, @Snibbler 

Both the `keywords` and `category` elements were added, and will be available in next release. As for the `poster` and `original_thumbnail` elements, those don't seem to be a part of the Media RSS namespace. I mentioned in #100 that support for custom elements in FeedKit would be a nice feature to have. However, that is still far in the future. 

Closing for now, thank you for your contribution.
