### ISSUE TITLE
Parsing of summary is broken

### ISSUE THREAD

**Issue by DarkDust** [nmdias/FeedKit#91]
The summary is not parsed correctly if it contains inline XML/HTML. Only whitespace is in the `value` property. For example this summary is not picked up:

```
  <summary type="xhtml">
<div xmlns="http://www.w3.org/1999/xhtml">
<p>Hello there!</p>
</div>
  </summary>
```

See for example a [GitLab activity feed](https://gitlab.com/gitlab-com/www-gitlab-com.atom).

**Comment by nmdias** [comment]
Hi, @DarkDust 

Thank you for the contribution. I won't be adding support for this anytime soon, as much as I'd like too see it in `FeedKit`. The solution you provided seems reasonable enough to consider, but would also need to be extended to other elements with an attribute of type xhtml, and remove the usage of XMLNode as it's only available for macOS.

Closing for now

Thanks
