### ISSUE TITLE
Different results on Heroku?

### ISSUE THREAD

**Issue by patwhitehead1** [nmdias/FeedKit#95]
I'm getting some strange behaviour when deploying my Kitura app to Heroku. Everything works fine with FeedKit when I run it locally, but when deployed I parse an RSS feed and feed.iTunes is nil. All other properties appear to be working as expected.

Any idea why this might happen?

**Comment by patwhitehead1** [comment]
Just wanted to follow up on this. Are there any reasons why RSSFeed.iTunes would ever be nil?

**Comment by patwhitehead1** [comment]
After lots of logging I was able to find the issue. Any place where the parser is expecting to see an iTunes tag (such as "/rss/channel/itunes:author"), the iTunes tag is reversed. So it looks like "/rss/channel/author:itunes" instead. Not sure why this is happening.

**Comment by nmdias** [comment]
Hi, @patwhitehead1 

I'll assume there was an issue with the feed being provided, as the `author `element is, as you pointed out, and as per [documentation](https://help.apple.com/itc/podcasts_connect/#/itcb54353390) `<itunes:author>` and not the other way around. Closing this for now.

Thanks

**Comment by patwhitehead1** [comment]
I think it's more how swift behaves with linux vs macOS, so likely nothing to do with the FeedKit library.
